version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # 前端端口
      - "3000:3000"  # API端口
    volumes:
      - /Users/jimmyluo/Downloads:/files  # 挂载宿主机文件系统，可以根据需要修改
    environment:
      - NODE_ENV=production
      - BASE_PATH=/files
    container_name: file-explorer
    restart: unless-stopped
