/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./components/explorer/Breadcrumbs.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CodeBlock: typeof import('./components/ui/CodeBlock.vue')['default']
    CompressProgressDialog: typeof import('./components/explorer/dialogs/CompressProgressDialog.vue')['default']
    ContextMenu: typeof import('./components/explorer/ContextMenu.vue')['default']
    CopyProgressDialog: typeof import('./components/explorer/dialogs/CopyProgressDialog.vue')['default']
    CreateFileDialog: typeof import('./components/explorer/dialogs/CreateFileDialog.vue')['default']
    CreateFolderDialog: typeof import('./components/explorer/dialogs/CreateFolderDialog.vue')['default']
    CreateLinkDialog: typeof import('./components/explorer/dialogs/CreateLinkDialog.vue')['default']
    DeleteDialog: typeof import('./components/explorer/dialogs/DeleteDialog.vue')['default']
    DeleteProgressDialog: typeof import('./components/explorer/dialogs/DeleteProgressDialog.vue')['default']
    Demo: typeof import('./components/ui/Demo.vue')['default']
    Dialog: typeof import('./components/ui/Dialog.vue')['default']
    DirectoryPickerDialog: typeof import('./components/explorer/dialogs/DirectoryPickerDialog.vue')['default']
    Dropdown: typeof import('./components/ui/Dropdown.vue')['default']
    DropdownItem: typeof import('./components/ui/DropdownItem.vue')['default']
    ExtractProgressDialog: typeof import('./components/explorer/dialogs/ExtractProgressDialog.vue')['default']
    FileGrid: typeof import('./components/explorer/FileGrid.vue')['default']
    FileList: typeof import('./components/explorer/FileList.vue')['default']
    HardLinkInfoDialog: typeof import('./components/explorer/dialogs/HardLinkInfoDialog.vue')['default']
    InfoDialog: typeof import('./components/explorer/dialogs/InfoDialog.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    Label: typeof import('./components/ui/Label.vue')['default']
    LinkProgressDialog: typeof import('./components/explorer/dialogs/LinkProgressDialog.vue')['default']
    Menu: typeof import('./components/ui/Menu.vue')['default']
    MenuItem: typeof import('./components/ui/MenuItem.vue')['default']
    MoveProgressDialog: typeof import('./components/explorer/dialogs/MoveProgressDialog.vue')['default']
    Navigation: typeof import('./components/ui/Navigation.vue')['default']
    PasswordInput: typeof import('./components/PasswordInput.vue')['default']
    PropertiesDialog: typeof import('./components/explorer/dialogs/PropertiesDialog.vue')['default']
    RenameDialog: typeof import('./components/explorer/dialogs/RenameDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./components/explorer/dialogs/SearchDialog.vue')['default']
    SearchResultsDialog: typeof import('./components/explorer/dialogs/SearchResultsDialog.vue')['default']
    SecurityDemo: typeof import('./components/SecurityDemo.vue')['default']
    SubMenu: typeof import('./components/ui/SubMenu.vue')['default']
    TabPane: typeof import('./components/ui/TabPane.vue')['default']
    Tabs: typeof import('./components/ui/Tabs.vue')['default']
    Toast: typeof import('./components/explorer/Toast.vue')['default']
    Toolbar: typeof import('./components/explorer/Toolbar.vue')['default']
    Tooltip: typeof import('./components/ui/Tooltip.vue')['default']
    Tree: typeof import('./components/ui/Tree.vue')['default']
    Upload: typeof import('./components/ui/Upload.vue')['default']
  }
}
